# Generated by Django 5.0.1 on 2024-02-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_remove_message_distribution_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mails',
            field=models.ManyToManyField(related_name='users', to='mailing.mailingservice', verbose_name='Рассылки'),
        ),
    ]
