# Generated by Django 5.0.1 on 2024-02-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_mailingservice_options_and_more'),
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clients',
            field=models.ManyToManyField(blank=True, null=True, to='mailing.client', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mails',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='mailing.mailingservice', verbose_name='Рассылки'),
        ),
    ]
