# Generated by Django 5.0.1 on 2024-02-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_clients_alter_user_mails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('set_active', 'Can set user active')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
