# Generated by Django 5.0.1 on 2024-02-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_mailingservice_creator_alter_client_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingservice',
            options={'permissions': [('set_mailing_status', 'Can set mailing status')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
