# Generated by Django 5.0.1 on 2024-02-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mailingservice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingservice',
            options={'permissions': [('set_active', 'Can set mailing active')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='mailingservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
